# =============================================================
# 02-priority-level-custom.yaml
# PriorityLevelConfigurations custom pour nos labs
#
# A appliquer AVANT les FlowSchemas qui les referencent
#
# Champs valides (flowcontrol.apiserver.k8s.io/v1) :
#   lendablePercent      : % de seats pretables aux autres niveaux
#   borrowingLimitPercent: % de seats empruntables aux autres niveaux
# =============================================================

---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: demo-priority
  labels:
    app.kubernetes.io/part-of: priority-tutorial
spec:
  type: Limited
  limited:
    nominalConcurrencyShares: 30
    limitResponse:
      type: Queue
      queuing:
        queues: 16
        handSize: 4
        queueLengthLimit: 10

---
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: PriorityLevelConfiguration
metadata:
  name: demo-restricted
  labels:
    app.kubernetes.io/part-of: priority-tutorial
spec:
  type: Limited
  limited:
    nominalConcurrencyShares: 5
    limitResponse:
      type: Queue
      queuing:
        queues: 4
        handSize: 2
        queueLengthLimit: 5
